# Generated by Django 3.2.15 on 2022-08-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_operatingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('env', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('crete_time_before', models.CharField(max_length=255)),
                ('crete_time_after', models.CharField(max_length=255)),
                ('submit_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='OperatingRecord',
        ),
    ]
